# Import required libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
import os
os.chdir("S:/Summer Internships/2020")

# Read the Dataset

In [3]:
data=pd.read_csv('kidney_disease.csv')
data

id   age    bp     sg   al   su     rbc        pc         pcc  \
0      0  48.0  80.0  1.020  1.0  0.0     NaN    normal  notpresent   
1      1   7.0  50.0  1.020  4.0  0.0     NaN    normal  notpresent   
2      2  62.0  80.0  1.010  2.0  3.0  normal    normal  notpresent   
3      3  48.0  70.0  1.005  4.0  0.0  normal  abnormal     present   
4      4  51.0  80.0  1.010  2.0  0.0  normal    normal  notpresent   
..   ...   ...   ...    ...  ...  ...     ...       ...         ...   
395  395  55.0  80.0  1.020  0.0  0.0  normal    normal  notpresent   
396  396  42.0  70.0  1.025  0.0  0.0  normal    normal  notpresent   
397  397  12.0  80.0  1.020  0.0  0.0  normal    normal  notpresent   
398  398  17.0  60.0  1.025  0.0  0.0  normal    normal  notpresent   
399  399  58.0  80.0  1.025  0.0  0.0  normal    normal  notpresent   

             ba  ...  pcv    wc   rc  htn   dm  cad appet   pe  ane  \
0    notpresent  ...   44  7800  5.2  yes  yes   no  good   no   no   
1    notpresent  ...   38  6000  NaN   no   no   no  good   no   no   
2    notpresent  ...   31  7500  NaN   no  yes   no  poor   no  yes   
3    notpresent  ...   32  6700  3.9  yes   no   no  poor  yes  yes   
4    notpresent  ...   35  7300  4.6   no   no   no  good   no   no   
..          ...  ...  ...   ...  ...  ...  ...  ...   ...  ...  ...   
395  notpresent  ...   47  6700  4.9   no   no   no  good   no   no   
396  notpresent  ...   54  7800  6.2   no   no   no  good   no   no   
397  notpresent  ...   49  6600  5.4   no   no   no  good   no   no   
398  notpresent  ...   51  7200  5.9   no   no   no  good   no   no   
399  notpresent  ...   53  6800  6.1   no   no   no  good   no   no   

    classification  
0              ckd  
1              ckd  
2              ckd  
3              ckd  
4              ckd  
..             ...  
395         notckd  
396         notckd  
397         notckd  
398         notckd  
399         notckd  

[400 rows x 26 columns]

# Shape of the Data

In [4]:
data.shape

(400, 26)

In [5]:
#Since Id is Not Required it is Dropped from the data
data=data.drop(['id'],axis=1)
data.head()

age    bp     sg   al   su     rbc        pc         pcc          ba  \
0  48.0  80.0  1.020  1.0  0.0     NaN    normal  notpresent  notpresent   
1   7.0  50.0  1.020  4.0  0.0     NaN    normal  notpresent  notpresent   
2  62.0  80.0  1.010  2.0  3.0  normal    normal  notpresent  notpresent   
3  48.0  70.0  1.005  4.0  0.0  normal  abnormal     present  notpresent   
4  51.0  80.0  1.010  2.0  0.0  normal    normal  notpresent  notpresent   

     bgr  ...  pcv    wc   rc  htn   dm cad appet   pe  ane classification  
0  121.0  ...   44  7800  5.2  yes  yes  no  good   no   no            ckd  
1    NaN  ...   38  6000  NaN   no   no  no  good   no   no            ckd  
2  423.0  ...   31  7500  NaN   no  yes  no  poor   no  yes            ckd  
3  117.0  ...   32  6700  3.9  yes   no  no  poor  yes  yes            ckd  
4  106.0  ...   35  7300  4.6   no   no  no  good   no   no            ckd  

[5 rows x 25 columns]

# Check For Any Null Values in the Data

In [6]:
data.isnull().any()

age                True
bp                 True
sg                 True
al                 True
su                 True
rbc                True
pc                 True
pcc                True
ba                 True
bgr                True
bu                 True
sc                 True
sod                True
pot                True
hemo               True
pcv                True
wc                 True
rc                 True
htn                True
dm                 True
cad                True
appet              True
pe                 True
ane                True
classification    False
dtype: bool

# Filling The NULL Values in the data replacing it with 0 and 1

In [7]:
#The Categorical Values in the Dataset are converted into Numerical Values For Better Representation of the Data

data['rbc'].fillna('normal',inplace = True)
data['rbc'].replace(['normal','abnormal'],[0,1],inplace = True)

data['pc'].fillna('normal',inplace = True)
data['pc'].replace(['normal','abnormal'],[0,1],inplace = True)

data['pcc'].fillna('notpresent',inplace = True)
data['pcc'].replace(['notpresent','present'],[0,1],inplace = True)

data['ba'].fillna('notpresent',inplace = True)
data['ba'].replace(['notpresent','present'],[0,1],inplace = True)

data['htn'].fillna('no',inplace = True)
data['htn'].replace(['no','yes'],[0,1],inplace = True)

data['dm'].fillna('no',inplace = True)
#Replacing '\tno','\tyes',' yes' with 'no','yes','yes'
data['dm'].replace(['\tno','\tyes',' yes'],['no','yes','yes'],inplace = True)
data['dm'].replace(['no','yes'],[0,1],inplace = True)

data['appet'].fillna('good',inplace = True)
data['appet'].replace(['good','poor'],[0,1],inplace = True)

data['pe'].fillna('no',inplace = True)
data['pe'].replace(['no','yes'],[0,1],inplace = True)

data['ane'].fillna('no',inplace = True)
data['ane'].replace(['no','yes'],[0,1],inplace = True)

In [8]:
data.head(5)

age    bp     sg   al   su  rbc  pc  pcc  ba    bgr  ...  pcv    wc   rc  \
0  48.0  80.0  1.020  1.0  0.0    0   0    0   0  121.0  ...   44  7800  5.2   
1   7.0  50.0  1.020  4.0  0.0    0   0    0   0    NaN  ...   38  6000  NaN   
2  62.0  80.0  1.010  2.0  3.0    0   0    0   0  423.0  ...   31  7500  NaN   
3  48.0  70.0  1.005  4.0  0.0    0   1    1   0  117.0  ...   32  6700  3.9   
4  51.0  80.0  1.010  2.0  0.0    0   0    0   0  106.0  ...   35  7300  4.6   

   htn  dm cad appet pe  ane  classification  
0    1   1  no     0  0    0             ckd  
1    0   0  no     0  0    0             ckd  
2    0   1  no     1  0    1             ckd  
3    1   0  no     1  1    1             ckd  
4    0   0  no     0  0    0             ckd  

[5 rows x 25 columns]

In [9]:
data['rbc'].value_counts()
data['pc'].value_counts()
data['pcc'].value_counts()
data['ba'].value_counts()
data['htn'].value_counts()
data['dm'].value_counts()
data['appet'].value_counts()
data['pe'].value_counts()
data['ane'].value_counts()

0    340
1     60
Name: ane, dtype: int64

# Replacing the values of '\t' and '\t43' with 52 and 43

In [10]:
data['pcv'].replace(['\t?','\t43'],[52,43],inplace = True)
data['pcv'].fillna(52,inplace = True)

In [11]:
data['pcv'].value_counts()

52    71
52    21
41    21
48    19
44    19
40    16
43    14
45    13
42    13
32    12
36    12
50    12
33    12
28    12
37    11
34    11
29     9
35     9
30     9
46     9
31     8
24     7
39     7
26     6
38     5
54     4
53     4
51     4
47     4
49     4
22     3
25     3
27     3
23     2
19     2
15     1
18     1
9      1
21     1
17     1
20     1
43     1
14     1
16     1
Name: pcv, dtype: int64

# Replacing the values '\t8400','\t6200','\t' with 8400,6200,9800 respectively

In [12]:
data['wc'].replace(['\t8400','\t6200','\t?'],[8400,6200,9800],inplace = True)
data['wc'].fillna(9800,inplace = True)

In [13]:
data['wc'].value_counts()

9800     106
9800      11
6700      10
9200       9
7200       9
        ... 
11800      1
4900       1
5900       1
16300      1
11200      1
Name: wc, Length: 92, dtype: int64

# Replacing and filling the values '\t' with 5.2

In [14]:
data['rc'].replace(['\t?'],[5.2],inplace = True)
data['rc'].fillna(5.2,inplace = True)

In [15]:
data['rc'].value_counts()

5.2    131
5.2     18
4.5     16
4.9     14
4.7     11
4.8     10
3.9     10
4.6      9
3.4      9
3.7      8
5.9      8
5.0      8
6.1      8
5.5      8
5.8      7
5.4      7
3.8      7
5.3      7
4.3      6
4.2      6
5.6      6
5.7      5
5.1      5
4.4      5
6.2      5
4.1      5
6.4      5
3.2      5
6.5      5
6.0      4
6.3      4
3.6      4
3.3      3
3.5      3
4.0      3
4        3
2.1      2
3.1      2
2.8      2
2.6      2
5        2
2.5      2
2.7      2
3.0      2
2.9      2
2.4      1
3        1
8.0      1
2.3      1
Name: rc, dtype: int64

# Replacing '\tno'' with 'no'

In [16]:
data['cad'].value_counts()

no      362
yes      34
\tno      2
Name: cad, dtype: int64

In [17]:
data['cad'].replace(['\tno'],['no'],inplace = True)
data['cad'].value_counts()

no     364
yes     34
Name: cad, dtype: int64

# Filling and Replacing up the Null Values with no and 0,1.

In [18]:
data['cad'].fillna('no',inplace = True)
data['cad'].replace(['no','yes'],[0,1],inplace = True)
data['cad'].value_counts()

0    366
1     34
Name: cad, dtype: int64

# Replacing ckd and notckd with 1,0 respectively.

In [19]:
data['classification'].replace(['ckd\t'],['ckd'],inplace=True)

data['classification'].value_counts()

ckd       250
notckd    150
Name: classification, dtype: int64

In [20]:
data['classification'].fillna('ckd',inplace = True)
data['classification'].replace(['ckd','notckd'],[0,1],inplace = True)
data['classification'].value_counts()

0    250
1    150
Name: classification, dtype: int64

# Converting Object values into float values.

In [21]:
data['rc']=data['rc'].astype('float')

data['pcv'] =data['pcv'].astype('float')

data['wc'] =data['wc'].astype('float')

In [22]:
data['rbc'].fillna('normal',inplace=True)
data['pc'].fillna('normal',inplace=True)
data['pcc'].fillna('notpresent',inplace=True)
data['ba'].fillna('notpresent',inplace=True)
data['htn'].fillna('no',inplace=True)
data['dm'].fillna('no',inplace=True)
data['cad'].fillna('no',inplace=True)
data['appet'].fillna('good',inplace=True)
data['pe'].fillna('no',inplace=True)
data['ane'].fillna('no',inplace=True)

In [23]:
data.dtypes

age               float64
bp                float64
sg                float64
al                float64
su                float64
rbc                 int64
pc                  int64
pcc                 int64
ba                  int64
bgr               float64
bu                float64
sc                float64
sod               float64
pot               float64
hemo              float64
pcv               float64
wc                float64
rc                float64
htn                 int64
dm                  int64
cad                 int64
appet               int64
pe                  int64
ane                 int64
classification      int64
dtype: object

In [24]:
data.isnull().any()

age                True
bp                 True
sg                 True
al                 True
su                 True
rbc               False
pc                False
pcc               False
ba                False
bgr                True
bu                 True
sc                 True
sod                True
pot                True
hemo               True
pcv               False
wc                False
rc                False
htn               False
dm                False
cad               False
appet             False
pe                False
ane               False
classification    False
dtype: bool

# Filling The Numerical values using Imputer Technique

In [25]:
features = data.iloc[:,:].values
features

array([[48.   , 80.   ,  1.02 , ...,  0.   ,  0.   ,  0.   ],
       [ 7.   , 50.   ,  1.02 , ...,  0.   ,  0.   ,  0.   ],
       [62.   , 80.   ,  1.01 , ...,  0.   ,  1.   ,  0.   ],
       ...,
       [12.   , 80.   ,  1.02 , ...,  0.   ,  0.   ,  1.   ],
       [17.   , 60.   ,  1.025, ...,  0.   ,  0.   ,  1.   ],
       [58.   , 80.   ,  1.025, ...,  0.   ,  0.   ,  1.   ]])

In [26]:
data.head()

age    bp     sg   al   su  rbc  pc  pcc  ba    bgr  ...   pcv      wc  \
0  48.0  80.0  1.020  1.0  0.0    0   0    0   0  121.0  ...  44.0  7800.0   
1   7.0  50.0  1.020  4.0  0.0    0   0    0   0    NaN  ...  38.0  6000.0   
2  62.0  80.0  1.010  2.0  3.0    0   0    0   0  423.0  ...  31.0  7500.0   
3  48.0  70.0  1.005  4.0  0.0    0   1    1   0  117.0  ...  32.0  6700.0   
4  51.0  80.0  1.010  2.0  0.0    0   0    0   0  106.0  ...  35.0  7300.0   

    rc  htn  dm  cad  appet  pe  ane  classification  
0  5.2    1   1    0      0   0    0               0  
1  5.2    0   0    0      0   0    0               0  
2  5.2    0   1    0      1   0    1               0  
3  3.9    1   0    0      1   1    1               0  
4  4.6    0   0    0      0   0    0               0  

[5 rows x 25 columns]

# Applying Imputation Technique to fill null values using Mean Technique

In [27]:
from sklearn.impute import SimpleImputer 
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')

In [28]:
imputer.fit(features[:,[0,1,2,3,4,9,10,11,12,13,14,15]])
features[:,[0,1,2,3,4,9,10,11,12,13,14,15]]=imputer.fit_transform(features[:,[0,1,2,3,4,9,10,11,12,13,14,15]])


In [29]:
new_data=pd.DataFrame(features)
new_data.isnull().any()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
dtype: bool

In [30]:
new_data.columns = ('age','bp','sg','al','su','rbc','pc','pcc','ba','bgr','bu','se','sod','pot','hemo','pcv','wc','rc','htn','dm','cad','appet','pe','ane','classification')
new_data.head()

age    bp     sg   al   su  rbc   pc  pcc   ba         bgr  ...   pcv  \
0  48.0  80.0  1.020  1.0  0.0  0.0  0.0  0.0  0.0  121.000000  ...  44.0   
1   7.0  50.0  1.020  4.0  0.0  0.0  0.0  0.0  0.0  148.036517  ...  38.0   
2  62.0  80.0  1.010  2.0  3.0  0.0  0.0  0.0  0.0  423.000000  ...  31.0   
3  48.0  70.0  1.005  4.0  0.0  0.0  1.0  1.0  0.0  117.000000  ...  32.0   
4  51.0  80.0  1.010  2.0  0.0  0.0  0.0  0.0  0.0  106.000000  ...  35.0   

       wc   rc  htn   dm  cad  appet   pe  ane  classification  
0  7800.0  5.2  1.0  1.0  0.0    0.0  0.0  0.0             0.0  
1  6000.0  5.2  0.0  0.0  0.0    0.0  0.0  0.0             0.0  
2  7500.0  5.2  0.0  1.0  0.0    1.0  0.0  1.0             0.0  
3  6700.0  3.9  1.0  0.0  0.0    1.0  1.0  1.0             0.0  
4  7300.0  4.6  0.0  0.0  0.0    0.0  0.0  0.0             0.0  

[5 rows x 25 columns]

In [31]:
new_data.shape

(400, 25)

# Data Correlation

In [32]:
new_data.corr()

age        bp        sg        al        su       rbc  \
age             1.000000  0.148004 -0.180570  0.114764  0.207857  0.011783   
bp              0.148004  1.000000 -0.182463  0.146593  0.200784  0.151369   
sg             -0.180570 -0.182463  1.000000 -0.466698 -0.287993 -0.236228   
al              0.114764  0.146593 -0.466698  1.000000  0.268070  0.373927   
su              0.207857  0.200784 -0.287993  0.268070  1.000000  0.074324   
rbc             0.011783  0.151369 -0.236228  0.373927  0.074324  1.000000   
pc              0.101951  0.156856 -0.345325  0.535157  0.168826  0.377394   
pcc             0.159074  0.059560 -0.290663  0.399749  0.151445  0.102948   
ba              0.043573  0.112173 -0.220792  0.367855  0.107684  0.184402   
bgr             0.214410  0.149100 -0.326339  0.326400  0.639186  0.153076   
bu              0.187544  0.183970 -0.278568  0.405778  0.152186  0.236322   
se              0.127316  0.144359 -0.213513  0.230479  0.130122  0.138394   
sod            -0.085949 -0.103220  0.242841 -0.271316 -0.073715 -0.140572   
pot             0.050148  0.066648 -0.061821  0.114427  0.181015 -0.018192   
hemo           -0.175380 -0.279535  0.531755 -0.549697 -0.191518 -0.280990   
pcv            -0.167598 -0.223762  0.392311 -0.408185 -0.154185 -0.232256   
wc              0.116554  0.039957 -0.243869  0.223967  0.165610  0.021104   
rc             -0.203129 -0.209598  0.383420 -0.393725 -0.157249 -0.166161   
htn             0.393440  0.270447 -0.366959  0.481724  0.293179  0.140538   
dm              0.363475  0.228250 -0.393190  0.378042  0.472330  0.145646   
cad             0.232951  0.086618 -0.154803  0.236745  0.246702  0.111493   
appet           0.157741  0.177601 -0.246822  0.330562  0.080648  0.160868   
pe              0.094434  0.054083 -0.272476  0.440893  0.130721  0.199285   
ane             0.050567  0.194962 -0.213276  0.282305  0.066348  0.107625   
classification -0.225405 -0.290600  0.698957 -0.599238 -0.327812 -0.282642   

                      pc       pcc        ba       bgr  ...       pcv  \
age             0.101951  0.159074  0.043573  0.214410  ... -0.167598   
bp              0.156856  0.059560  0.112173  0.149100  ... -0.223762   
sg             -0.345325 -0.290663 -0.220792 -0.326339  ...  0.392311   
al              0.535157  0.399749  0.367855  0.326400  ... -0.408185   
su              0.168826  0.151445  0.107684  0.639186  ... -0.154185   
rbc             0.377394  0.102948  0.184402  0.153076  ... -0.232256   
pc              1.000000  0.520118  0.330401  0.262259  ... -0.360741   
pcc             0.520118  1.000000  0.275082  0.197593  ... -0.278041   
ba              0.330401  0.275082  1.000000  0.085940  ... -0.160221   
bgr             0.262259  0.197593  0.085940  1.000000  ... -0.193700   
bu              0.344048  0.184415  0.158444  0.127489  ... -0.417129   
se              0.157896  0.049940  0.050830  0.082242  ... -0.248241   
sod            -0.173323 -0.142135 -0.081733 -0.154393  ...  0.279224   
pot             0.158750 -0.006316 -0.002688  0.056695  ... -0.071654   
hemo           -0.411500 -0.275763 -0.204954 -0.269149  ...  0.658212   
pcv            -0.360741 -0.278041 -0.160221 -0.193700  ...  1.000000   
wc              0.107753  0.158224  0.095702  0.137186  ... -0.095653   
rc             -0.365479 -0.238772 -0.186593 -0.194327  ...  0.616166   
htn             0.291719  0.195623  0.089046  0.369849  ... -0.466613   
dm              0.201032  0.165236  0.080070  0.500618  ... -0.346144   
cad             0.172295  0.188029  0.162395  0.212433  ... -0.275903   
appet           0.274985  0.189688  0.149126  0.176132  ... -0.252915   
pe              0.350227  0.104356  0.134732  0.101502  ... -0.279413   
ane             0.260566  0.175861  0.052208  0.126854  ... -0.444377   
classification -0.375154 -0.265313 -0.186871 -0.401374  ...  0.427353   

                      wc        rc       htn        dm       cad     appet  \
age            

In [33]:
x = new_data.iloc[:,0:24]
y = new_data.iloc[:,24]

In [34]:
x

age    bp     sg   al   su  rbc   pc  pcc   ba         bgr  ...  hemo  \
0    48.0  80.0  1.020  1.0  0.0  0.0  0.0  0.0  0.0  121.000000  ...  15.4   
1     7.0  50.0  1.020  4.0  0.0  0.0  0.0  0.0  0.0  148.036517  ...  11.3   
2    62.0  80.0  1.010  2.0  3.0  0.0  0.0  0.0  0.0  423.000000  ...   9.6   
3    48.0  70.0  1.005  4.0  0.0  0.0  1.0  1.0  0.0  117.000000  ...  11.2   
4    51.0  80.0  1.010  2.0  0.0  0.0  0.0  0.0  0.0  106.000000  ...  11.6   
..    ...   ...    ...  ...  ...  ...  ...  ...  ...         ...  ...   ...   
395  55.0  80.0  1.020  0.0  0.0  0.0  0.0  0.0  0.0  140.000000  ...  15.7   
396  42.0  70.0  1.025  0.0  0.0  0.0  0.0  0.0  0.0   75.000000  ...  16.5   
397  12.0  80.0  1.020  0.0  0.0  0.0  0.0  0.0  0.0  100.000000  ...  15.8   
398  17.0  60.0  1.025  0.0  0.0  0.0  0.0  0.0  0.0  114.000000  ...  14.2   
399  58.0  80.0  1.025  0.0  0.0  0.0  0.0  0.0  0.0  131.000000  ...  15.8   

      pcv      wc   rc  htn   dm  cad  appet   pe  ane  
0    44.0  7800.0  5.2  1.0  1.0  0.0    0.0  0.0  0.0  
1    38.0  6000.0  5.2  0.0  0.0  0.0    0.0  0.0  0.0  
2    31.0  7500.0  5.2  0.0  1.0  0.0    1.0  0.0  1.0  
3    32.0  6700.0  3.9  1.0  0.0  0.0    1.0  1.0  1.0  
4    35.0  7300.0  4.6  0.0  0.0  0.0    0.0  0.0  0.0  
..    ...     ...  ...  ...  ...  ...    ...  ...  ...  
395  47.0  6700.0  4.9  0.0  0.0  0.0    0.0  0.0  0.0  
396  54.0  7800.0  6.2  0.0  0.0  0.0    0.0  0.0  0.0  
397  49.0  6600.0  5.4  0.0  0.0  0.0    0.0  0.0  0.0  
398  51.0  7200.0  5.9  0.0  0.0  0.0    0.0  0.0  0.0  
399  53.0  6800.0  6.1  0.0  0.0  0.0    0.0  0.0  0.0  

[400 rows x 24 columns]

In [35]:
y

0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
      ... 
395    1.0
396    1.0
397    1.0
398    1.0
399    1.0
Name: classification, Length: 400, dtype: float64

To convert series values to Array Format for Onehot Encoding

In [36]:
x=new_data.iloc[:,0:24].values
y=new_data.iloc[:,24].values
type(x)

numpy.ndarray

In [37]:
x.shape

(400, 24)

In [38]:
y.reshape(-1,1)

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],

# Normalising the data.

In [39]:
from sklearn import preprocessing
minmax = preprocessing.MinMaxScaler(feature_range=(0,1))
minmax.fit(x).transform(x)

array([[0.52272727, 0.23076923, 0.75      , ..., 0.        , 0.        ,
        0.        ],
       [0.05681818, 0.        , 0.75      , ..., 0.        , 0.        ,
        0.        ],
       [0.68181818, 0.23076923, 0.25      , ..., 1.        , 0.        ,
        1.        ],
       ...,
       [0.11363636, 0.23076923, 0.75      , ..., 0.        , 0.        ,
        0.        ],
       [0.17045455, 0.07692308, 1.        , ..., 0.        , 0.        ,
        0.        ],
       [0.63636364, 0.23076923, 1.        , ..., 0.        , 0.        ,
        0.        ]])

Train Test Split

In [40]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size  = 0.2)

In [41]:
x_train

array([[64.        , 90.        ,  1.015     , ...,  0.        ,
         0.        ,  1.        ],
       [54.        , 80.        ,  1.01      , ...,  1.        ,
         1.        ,  0.        ],
       [51.48337596, 70.        ,  1.01740793, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [44.        , 70.        ,  1.01740793, ...,  0.        ,
         0.        ,  0.        ],
       [62.        , 90.        ,  1.015     , ...,  0.        ,
         1.        ,  1.        ],
       [68.        , 70.        ,  1.01      , ...,  0.        ,
         0.        ,  0.        ]])

In [42]:
x_test

array([[ 34.   ,  60.   ,   1.02 , ...,   0.   ,   0.   ,   0.   ],
       [ 59.   , 100.   ,   1.02 , ...,   1.   ,   1.   ,   0.   ],
       [ 41.   ,  70.   ,   1.02 , ...,   0.   ,   0.   ,   0.   ],
       ...,
       [ 45.   ,  80.   ,   1.02 , ...,   1.   ,   0.   ,   0.   ],
       [ 71.   ,  70.   ,   1.01 , ...,   0.   ,   0.   ,   0.   ],
       [ 34.   ,  70.   ,   1.025, ...,   0.   ,   0.   ,   0.   ]])

In [43]:
y_train

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1.,
       0., 1., 1., 0., 0., 1., 1., 0., 1., 0., 0., 1., 0., 1., 0., 1., 1.,
       1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 1., 0., 0.,
       1., 0., 0., 1., 1., 0., 0., 1., 1., 0., 1., 0., 0., 0., 0., 0., 1.,
       0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 1., 1.,
       0., 1., 0., 0., 1., 0., 0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 0.,
       0., 0., 0., 1., 1., 0., 1., 0., 0., 0., 0., 1., 1., 1., 0., 1., 0.,
       1., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 1., 0., 0., 1., 0., 0.,
       1., 0., 1., 1., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 1., 1., 1., 1., 0., 0.,
       0., 1., 0., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1., 0., 0., 1.,
       1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 1., 1., 0., 0., 1., 1., 1.,
       0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 1., 0.

In [44]:
y_test

array([1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1., 1., 0.,
       1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 0., 1., 0.,
       0., 1., 1., 0., 1., 0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       1., 0., 0., 1., 1., 1., 0., 1., 0., 0., 0., 1.])

In [45]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform (x_test)

In [46]:
x_train

array([[ 0.76948034,  0.97609076, -0.46253637, ..., -0.4853053 ,
        -0.47545099,  2.47206616],
       [ 0.16753265,  0.24780752, -1.38844517, ...,  2.06055857,
         2.10326623, -0.40451992],
       [ 0.01604504, -0.48047571, -0.01663128, ..., -0.4853053 ,
        -0.47545099, -0.40451992],
       ...,
       [-0.43441505, -0.48047571, -0.01663128, ..., -0.4853053 ,
        -0.47545099, -0.40451992],
       [ 0.6490908 ,  0.97609076, -0.46253637, ..., -0.4853053 ,
         2.10326623,  2.47206616],
       [ 1.01025942, -0.48047571, -1.38844517, ..., -0.4853053 ,
        -0.47545099, -0.40451992]])

In [47]:
x_test

array([[-1.03636275, -1.20875895,  0.46337244, ..., -0.4853053 ,
        -0.47545099, -0.40451992],
       [ 0.4685065 ,  1.70437399,  0.46337244, ...,  2.06055857,
         2.10326623, -0.40451992],
       [-0.61499936, -0.48047571,  0.46337244, ..., -0.4853053 ,
        -0.47545099, -0.40451992],
       ...,
       [-0.37422028,  0.24780752,  0.46337244, ...,  2.06055857,
        -0.47545099, -0.40451992],
       [ 1.19084373, -0.48047571, -1.38844517, ..., -0.4853053 ,
        -0.47545099, -0.40451992],
       [-1.03636275, -0.48047571,  1.38928125, ..., -0.4853053 ,
        -0.47545099, -0.40451992]])

In [48]:
y_test

array([1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1., 1., 0.,
       1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 0., 1., 0.,
       0., 1., 1., 0., 1., 0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       1., 0., 0., 1., 1., 1., 0., 1., 0., 0., 0., 1.])

In [49]:
y_train

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1.,
       0., 1., 1., 0., 0., 1., 1., 0., 1., 0., 0., 1., 0., 1., 0., 1., 1.,
       1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 1., 0., 0.,
       1., 0., 0., 1., 1., 0., 0., 1., 1., 0., 1., 0., 0., 0., 0., 0., 1.,
       0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 1., 1.,
       0., 1., 0., 0., 1., 0., 0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 0.,
       0., 0., 0., 1., 1., 0., 1., 0., 0., 0., 0., 1., 1., 1., 0., 1., 0.,
       1., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 1., 0., 0., 1., 0., 0.,
       1., 0., 1., 1., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 1., 1., 1., 1., 0., 0.,
       0., 1., 0., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1., 0., 0., 1.,
       1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 1., 1., 0., 0., 1., 1., 1.,
       0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 1., 0.

In [50]:
x_test.shape

(80, 24)

In [51]:
y_test.shape

(80,)

# ANN

In [52]:
import keras
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [53]:
classifier = Sequential()

In [54]:
classifier.add(Dense(units = 24, init = 'uniform', activation = 'relu'))

In [55]:
classifier.add(Dense(units = 12, init = 'uniform', activation = 'relu'))

In [56]:
classifier.add(Dense(units = 1, init = 'uniform', activation = 'sigmoid'))

In [57]:
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ["accuracy"])

In [58]:
classifier.fit(x_train, y_train, batch_size = 16, epochs = 20)




Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where

Epoch 1/20
320/320 [==============================] - 1s 2ms/step - loss: 0.6909 - acc: 0.5906
Epoch 2/20
320/320 [==============================] - 0s 88us/step - loss: 0.6777 - acc: 0.6156
Epoch 3/20
320/320 [==============================] - 0s 72us/step - loss: 0.6329 - acc: 0.8938
Epoch 4/20
320/320 [==============================] - 0s 85us/step - loss: 0.5374 - acc: 0.9469
Epoch 5/20
320/320 [==============================] - 0s 92us/step - loss: 0.4225 - acc: 0.9187
Epoch 6/20
320/320 [==============================] - 0s 96us/step - loss: 0.3245 - acc: 0.9094
Epoch 7/20
320/320 [==============================] - 0s 100us/step - loss: 0.2533 - acc: 0.9094
Epoch 8/20
320/320 [==============================] - 0s 160us/step - loss: 0.2043 - acc: 0.9156
Epoch 9/20
320/320 [==============================] - 0s 76us/step - loss: 0.1679 - acc: 0.9281
Epoch 10/20
320/320 [================

In [59]:
y_pred = classifier.predict(x_test)
# False means 0 else it is 1
y_pred = (y_pred>0.5)

In [60]:
from sklearn.metrics import accuracy_score
accuracy=accuracy_score(y_test,y_pred)
accuracy

0.975

In [61]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
cm

array([[51,  2],
       [ 0, 27]], dtype=int64)

In [62]:
classifier.save('kidney_disease.h5')

# Done!